"""
Build the GitHub Pages site directory from a finished CI run's reports.

Layout:
  gh-pages-site/
    index.html                  — landing page with stats + links to everything
    report.html                 — full master consolidated bug report
    agents/
      qa01-functional.html      — per-agent reports (links from index)
      qa02-edge.html
      ...
    history/
      index.html                — list of past runs
      run-NN.html               — archived master report for run NN
      run-NN/
        agents/                 — archived per-agent reports for run NN

Run AFTER consolidate_reports.py has run (so reports/bug-report.html exists)
and AFTER all agent artifacts have been downloaded into reports/.
"""
from __future__ import annotations
import json, os, re, shutil, sys
from pathlib import Path
from datetime import datetime

ROOT        = Path(__file__).parent.parent
REPORTS_DIR = ROOT / "reports"
SITE_DIR    = ROOT / "gh-pages-site"
RUN_NUMBER  = os.getenv("GITHUB_RUN_NUMBER", "0")
RUN_URL     = os.getenv("GITHUB_RUN_URL",
                        f"https://github.com/{os.getenv('GITHUB_REPOSITORY','')}/actions/runs/{os.getenv('GITHUB_RUN_ID','')}")
COMMIT_SHA  = (os.getenv("GITHUB_SHA", "") or "")[:7]
COMMIT_MSG  = os.getenv("GITHUB_COMMIT_MESSAGE", "")  # set in workflow


# ─── Per-agent report mapping ─────────────────────────────────────────────────
# Each entry: (custom_source_filename, public_filename, link_label, emoji)
# We prefer the Mehad-styled custom report (`agent-<src>.html`) generated by
# consolidate_reports.py over the default pytest-html outputs which don't
# match our UI design.
AGENT_REPORTS = [
    ("agent-qa01_functional.html",    "qa01-functional.html",   "QA-01 Functional",          "🧪"),
    ("agent-qa02_edge.html",          "qa02-edge.html",         "QA-02 Edge Cases",          "🔍"),
    ("agent-qa03_security.html",      "qa03-security.html",     "QA-03 Security",            "🔒"),
    ("agent-qa04_performance.html",   "qa04-performance.html",  "QA-04 Performance",         "⚡"),
    ("agent-qa05_hallucination.html", "qa05-hallucination.html","QA-05 Hallucination/Data",  "🧠"),
    ("agent-qa06_api.html",           "qa06-api.html",          "QA-06 API & Network",       "🌐"),
    ("agent-qa07_accessibility.html", "qa07-accessibility.html","QA-07 Accessibility",       "♿"),
    ("agent-qa08_mobile.html",        "qa08-mobile.html",       "QA-08 Mobile / Viewport",   "📱"),
    ("agent-qa09_seo.html",           "qa09-seo.html",          "QA-09 SEO & Meta",          "🔎"),
    ("agent-qa10_i18n.html",          "qa10-i18n.html",         "QA-10 i18n & RTL",          "🌏"),
    ("agent-qa11_visual.html",          "qa11-visual.html",          "QA-11 Visual Regression",   "🎨"),
    ("agent-qa12_js_errors.html",       "qa12-js-errors.html",       "QA-12 JS Error Sweeper",    "🐞"),
    ("agent-qa13_security_headers.html","qa13-security-headers.html","QA-13 Security Headers",    "🛡️"),
    ("agent-qa14_cookies.html",         "qa14-cookies.html",         "QA-14 Cookie Security",     "🍪"),
    ("agent-qa15_owasp.html",           "qa15-owasp.html",           "QA-15 OWASP Surface",       "🎯"),
    ("agent-qa16_lighthouse.html",      "qa16-lighthouse.html",      "QA-16 Core Web Vitals",     "📊"),
    ("agent-qa17_memory.html",          "qa17-memory.html",          "QA-17 Memory Leak",         "💧"),
    ("agent-qa18_network.html",         "qa18-network.html",         "QA-18 Network Resilience",  "📡"),
    ("agent-qa19_exploratory.html",     "qa19-exploratory.html",     "QA-19 Autonomous Explorer", "🤖"),
    ("agent-qa20_fuzzing.html",         "qa20-fuzzing.html",         "QA-20 Property-Based Fuzz", "🎲"),
    ("agent-qa22_vision.html",          "qa22-vision.html",          "QA-22 Vision-LLM UI Review","👁️"),
    ("agent-login.html",                "ai-test-agent.html",        "AI Test Agent (auto-gen)",  "🛠️"),
]


def _load_summary() -> dict:
    p = REPORTS_DIR / "consolidated_summary.json"
    if not p.exists():
        return {}
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _has_agent_report(*filenames: str) -> Path | None:
    """Find an agent's html report by trying multiple filename candidates.
    Walks REPORTS_DIR (artifacts may extract under nested subdirs)."""
    for filename in filenames:
        direct = REPORTS_DIR / filename
        if direct.exists():
            return direct
        for hit in REPORTS_DIR.rglob(filename):
            if hit.is_file():
                return hit
    return None


def _existing_history(site: Path) -> list[tuple[int, Path]]:
    """Return [(run_num, path), ...] for historical reports, sorted desc."""
    history_dir = site / "history"
    if not history_dir.exists():
        return []
    out = []
    for p in history_dir.glob("run-*.html"):
        m = re.match(r"run-(\d+)\.html", p.name)
        if m:
            out.append((int(m.group(1)), p))
    out.sort(reverse=True)
    return out


def _stat_box(label: str, value, klass: str, link_hash: str = "") -> str:
    """Build one stat card. If link_hash is set, the card is a link to
    report.html#<hash> which auto-applies the matching filter."""
    if link_hash:
        return (f'<a class="stat {klass}" href="report.html{link_hash}">'
                f'<div class="lbl">{label}</div>'
                f'<div class="val">{value}</div></a>')
    return (f'<div class="stat {klass}">'
            f'<div class="lbl">{label}</div>'
            f'<div class="val">{value}</div></div>')


def _agent_card(custom_src: str, public_name: str, label: str, emoji: str) -> str:
    has = _has_agent_report(custom_src, public_name) is not None
    if has:
        return (f'<a class="agent-card" href="agents/{public_name}">'
                f'<div class="emoji">{emoji}</div>'
                f'<div class="lbl">{label}</div>'
                f'<div class="cta">View report →</div></a>')
    return (f'<div class="agent-card disabled" title="Report not generated this run">'
            f'<div class="emoji">{emoji}</div>'
            f'<div class="lbl">{label}</div>'
            f'<div class="cta muted">No data</div></div>')


def _history_table(history: list[tuple[int, Path]]) -> str:
    if not history:
        return ('<p style="color:#8b949e;text-align:center;padding:30px">'
                'No previous runs archived yet — this is the first deployment.</p>')
    rows = []
    for run_num, _path in history[:50]:  # show last 50 runs
        rows.append(
            f'<tr><td>Run #{run_num}</td>'
            f'<td><a href="history/run-{run_num}.html">View report</a></td></tr>'
        )
    return (
        '<table class="history-table">'
        '<thead><tr><th>Run</th><th>Report</th></tr></thead>'
        f'<tbody>{"".join(rows)}</tbody></table>'
    )


def _load_trends() -> dict:
    """Load reports/trends.json — populated by consolidate_reports.py."""
    p = REPORTS_DIR / "trends.json"
    if not p.exists():
        return {}
    try:
        import json as _j
        return _j.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _detect_regressions(runs: list[dict]) -> list[str]:
    """Compare the most recent run against the previous one. Returns a
    list of human-readable regression messages."""
    if len(runs) < 2:
        return []
    cur = runs[-1]; prev = runs[-2]
    alerts: list[str] = []

    def _pct(s: str) -> float | None:
        if not s or not s.endswith("%"):
            return None
        try:
            return float(s.rstrip("%"))
        except ValueError:
            return None

    cur_rate, prev_rate = _pct(cur.get("pass_rate", "")), _pct(prev.get("pass_rate", ""))
    if cur_rate is not None and prev_rate is not None:
        delta = cur_rate - prev_rate
        if delta <= -2.0:
            alerts.append(
                f"⚠️ Pass rate dropped {abs(delta):.1f}% "
                f"({prev_rate:.1f}% → {cur_rate:.1f}%) since run #{prev['run_number']}"
            )
    cur_bugs = cur.get("bugs", 0)
    prev_bugs = prev.get("bugs", 0)
    if cur_bugs > prev_bugs + 2:
        alerts.append(
            f"⚠️ Bug count jumped {prev_bugs} → {cur_bugs} "
            f"(+{cur_bugs - prev_bugs} new) since run #{prev['run_number']}"
        )
    cur_failed = cur.get("failed", 0)
    prev_failed = prev.get("failed", 0)
    if cur_failed > prev_failed + 3:
        alerts.append(
            f"⚠️ Failed-test count jumped {prev_failed} → {cur_failed} "
            f"(+{cur_failed - prev_failed}) since run #{prev['run_number']}"
        )
    return alerts


def _trend_chart_html(trends: dict) -> str:
    """SVG sparkline + summary card. Pure-HTML so no external chart library
    needed. Shows last 30 runs of pass-rate + bug-count."""
    runs = trends.get("runs", [])[-30:]
    if not runs:
        return ""

    # Compute pass rate per run as float
    points = []
    for r in runs:
        rate = r.get("pass_rate", "")
        if not (isinstance(rate, str) and rate.endswith("%")):
            continue
        try:
            v = float(rate.rstrip("%"))
        except ValueError:
            continue
        points.append((r["run_number"], v, r.get("failed", 0), r.get("bugs", 0)))

    if not points:
        return ""

    # SVG sparkline for pass rate
    w, h, pad = 720, 110, 24
    inner_w = w - 2 * pad
    inner_h = h - 2 * pad
    n = len(points)
    if n == 1:
        path_d = f"M {pad} {pad + inner_h / 2} L {pad + inner_w} {pad + inner_h / 2}"
        circles = f'<circle cx="{pad + inner_w/2}" cy="{pad + inner_h/2}" r="4" fill="#3fb950"/>'
    else:
        coords = []
        for i, (run_num, rate, failed, bugs) in enumerate(points):
            x = pad + (inner_w * i / (n - 1))
            # Pass rate 0..100 → y inner_h..0
            y = pad + (inner_h * (1 - rate / 100.0))
            coords.append((x, y, run_num, rate, failed, bugs))
        path_d = "M " + " L ".join(f"{x:.1f} {y:.1f}" for x, y, *_ in coords)
        circles = "".join(
            f'<circle cx="{x:.1f}" cy="{y:.1f}" r="3" '
            f'fill="{"#3fb950" if r >= 95 else "#d29922" if r >= 85 else "#f85149"}">'
            f'<title>Run #{rn}: {r:.1f}% pass · {f} failed · {b} bugs</title>'
            f'</circle>'
            for x, y, rn, r, f, b in coords
        )

    last = points[-1]
    last_rate = last[1]
    rate_color = "#3fb950" if last_rate >= 95 else "#d29922" if last_rate >= 85 else "#f85149"

    alerts = _detect_regressions(runs)
    alerts_html = ""
    if alerts:
        items = "".join(f'<li>{a}</li>' for a in alerts)
        alerts_html = f"""
<div class="trend-alerts">
  <div class="trend-alerts-title">📉 Regression alerts</div>
  <ul>{items}</ul>
</div>"""

    return f"""
<h2>📊 Trend ({len(points)} run(s))</h2>
<div class="trend-card">
  <div class="trend-summary">
    <div>
      <div class="trend-label">Latest pass rate</div>
      <div class="trend-value" style="color:{rate_color}">{last_rate:.1f}%</div>
    </div>
    <div>
      <div class="trend-label">Latest run</div>
      <div class="trend-value">#{last[0]}</div>
    </div>
    <div>
      <div class="trend-label">Total failures</div>
      <div class="trend-value">{last[2]}</div>
    </div>
    <div>
      <div class="trend-label">Bug tickets</div>
      <div class="trend-value">{last[3]}</div>
    </div>
  </div>
  <svg viewBox="0 0 {w} {h}" class="trend-svg" preserveAspectRatio="none">
    <line x1="{pad}" y1="{pad + inner_h * 0.05}" x2="{pad + inner_w}" y2="{pad + inner_h * 0.05}" stroke="#30363d" stroke-dasharray="2,2"/>
    <line x1="{pad}" y1="{pad + inner_h * 0.5}"  x2="{pad + inner_w}" y2="{pad + inner_h * 0.5}" stroke="#30363d" stroke-dasharray="2,2"/>
    <text x="{pad - 4}" y="{pad + inner_h * 0.05 + 4}" fill="#8b949e" font-size="10" text-anchor="end">100%</text>
    <text x="{pad - 4}" y="{pad + inner_h * 0.5 + 4}" fill="#8b949e" font-size="10" text-anchor="end">50%</text>
    <text x="{pad - 4}" y="{pad + inner_h + 2}" fill="#8b949e" font-size="10" text-anchor="end">0%</text>
    <path d="{path_d}" fill="none" stroke="#58a6ff" stroke-width="2"/>
    {circles}
  </svg>
  {alerts_html}
</div>"""


def _build_index_html(summary: dict, history: list[tuple[int, Path]]) -> str:
    p   = summary.get("total_passed", 0)
    f   = summary.get("total_failed", 0)
    t   = summary.get("total_tests", 0)
    rate= summary.get("pass_rate", "—")
    bugs= summary.get("total_bugs", 0)
    sources = summary.get("sources", [])
    base_url = summary.get("base_url", "")
    when = summary.get("timestamp", "")
    when_short = when[:19].replace("T", " ") if when else ""

    rate_klass = "pass" if (isinstance(rate, str) and rate.endswith("%")
                            and float(rate.rstrip("%")) >= 95) else "warn"

    stats_html = (
        _stat_box("Passed",     p,             "pass",       "#passed") +
        _stat_box("Failed",     f,             "fail" if f else "ok", "#failed") +
        _stat_box("Total Tests", t,            "total",      "#all-tests") +
        _stat_box("Pass Rate",  rate,          rate_klass,   "#tests") +
        _stat_box("Bug Tickets", bugs,         "fail" if bugs else "ok", "#bugs") +
        _stat_box("Sources",    len(sources),  "total",      "#summary-table")
    )
    agent_grid = "".join(_agent_card(src, pub, lbl, em)
                         for src, pub, lbl, em in AGENT_REPORTS)

    history_html = _history_table(history)
    trend_html   = _trend_chart_html(_load_trends())

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Mehad QA — Run #{RUN_NUMBER}</title>
<link rel="icon" href="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxMDAgMTAwIj48dGV4dCB5PSIuOWVtIiBmb250LXNpemU9IjkwIj7wn6SWPC90ZXh0Pjwvc3ZnPg=="/>
<style>
  * {{ box-sizing:border-box }}
  body {{
    font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;
    background:#0d1117; color:#e6edf3; margin:0; padding:0; line-height:1.5;
  }}
  .hero {{
    background:linear-gradient(135deg,#1f6feb 0%,#7c3aed 100%);
    padding:48px 32px; border-bottom:1px solid #30363d;
  }}
  .hero-inner {{ max-width:1100px; margin:0 auto }}
  .hero h1 {{ margin:0 0 8px; font-size:32px; font-weight:700; letter-spacing:-.5px }}
  .hero .sub {{ color:#cdd9e5; font-size:15px; margin-top:6px }}
  .hero .meta {{ color:rgba(255,255,255,.85); font-size:13px; margin-top:18px;
                 display:flex; flex-wrap:wrap; gap:18px }}
  .hero .meta a {{ color:#fff; text-decoration:underline }}
  .wrap {{ max-width:1100px; margin:0 auto; padding:32px }}
  .stats {{
    display:grid; grid-template-columns:repeat(auto-fit,minmax(150px,1fr));
    gap:14px; margin-bottom:36px;
  }}
  .stat {{
    background:#161b22; border:1px solid #30363d; border-radius:8px;
    padding:18px 20px; position:relative;
    /* clickable card (when rendered as <a>) */
    text-decoration:none; color:inherit; display:block; cursor:pointer;
    transition:transform .12s, border-color .12s, background .12s, box-shadow .12s;
  }}
  a.stat:hover {{ border-color:#58a6ff; background:#1c2333;
                  transform:translateY(-2px);
                  box-shadow:0 4px 16px rgba(88,166,255,.12) }}
  a.stat::after {{
    content:"→"; position:absolute; right:14px; top:14px;
    color:#58a6ff; font-size:14px; font-weight:700;
    opacity:0; transition:opacity .15s, transform .15s;
  }}
  a.stat:hover::after {{ opacity:1; transform:translateX(2px) }}
  .stat .lbl {{ font-size:11px; text-transform:uppercase; letter-spacing:.6px;
              color:#8b949e; font-weight:600 }}
  .stat .val {{ font-size:30px; font-weight:700; margin-top:4px }}
  .stat.pass .val {{ color:#3fb950 }}
  .stat.fail .val {{ color:#f85149 }}
  .stat.warn .val {{ color:#d29922 }}
  .stat.ok .val   {{ color:#3fb950 }}
  .stat.total .val{{ color:#58a6ff }}
  h2 {{ font-size:18px; margin:32px 0 16px; padding-bottom:10px;
        border-bottom:1px solid #30363d }}
  .primary-cta {{
    display:block; padding:24px 30px; background:#1f6feb;
    border-radius:10px; color:#fff; text-decoration:none; font-size:16px;
    font-weight:600; margin-bottom:36px; transition:background .15s;
  }}
  .primary-cta:hover {{ background:#388bfd }}
  .primary-cta .cta-sub {{ font-size:12px; font-weight:400; opacity:.9;
                          margin-top:4px }}
  .agent-grid {{
    display:grid; grid-template-columns:repeat(auto-fit,minmax(240px,1fr));
    gap:14px;
  }}
  .agent-card {{
    background:#161b22; border:1px solid #30363d; border-radius:8px;
    padding:20px; text-decoration:none; color:#e6edf3; display:block;
    transition:transform .12s,border-color .12s,background .12s;
  }}
  .agent-card:hover {{ border-color:#58a6ff; background:#1c2333; transform:translateY(-2px) }}
  .agent-card.disabled {{ opacity:.55; cursor:not-allowed }}
  .agent-card .emoji {{ font-size:28px; margin-bottom:8px }}
  .agent-card .lbl   {{ font-weight:600; font-size:14px; margin-bottom:4px }}
  .agent-card .cta   {{ font-size:12px; color:#58a6ff }}
  .agent-card .cta.muted {{ color:#8b949e }}
  .history-table {{
    width:100%; border-collapse:collapse; background:#161b22;
    border-radius:8px; overflow:hidden;
  }}
  .history-table th, .history-table td {{
    padding:11px 18px; text-align:left; border-bottom:1px solid #30363d;
    font-size:13px;
  }}
  .history-table th {{ background:#0d1117; font-size:11px;
                       text-transform:uppercase; letter-spacing:.5px;
                       color:#8b949e }}
  .history-table tr:last-child td {{ border-bottom:none }}
  .history-table tr:hover td {{ background:#1c2333 }}
  .history-table a {{ color:#58a6ff; text-decoration:none }}
  .history-table a:hover {{ text-decoration:underline }}
  .footer {{ margin-top:44px; padding:24px 20px; text-align:center;
             color:#8b949e; font-size:12px; border-top:1px solid #30363d }}
  .footer .contact-card {{
    display:inline-flex; flex-direction:column; align-items:center;
    gap:6px; padding:18px 28px; margin:14px auto 0;
    background:#161b22; border:1px solid #30363d; border-radius:10px;
  }}
  .footer .contact-card .name  {{ font-weight:700; font-size:15px; color:#e6edf3 }}
  .footer .contact-card .title {{ font-size:12px; color:#8b949e }}
  .footer .contact-card .links a {{
    display:inline-block; color:#58a6ff; text-decoration:none;
    font-size:12px; padding:5px 14px; margin-top:8px;
    border:1px solid #30363d; border-radius:6px; background:#0d1117;
    transition:background .15s, border-color .15s;
  }}
  .footer .contact-card .links a:hover {{
    background:#1c2333; border-color:#58a6ff;
  }}

  /* Responsive — tablet + mobile breakpoints */
  @media (max-width:768px) {{
    .hero {{ padding:30px 18px }}
    .hero h1 {{ font-size:24px }}
    .hero .meta {{ flex-direction:column; gap:8px; font-size:12px }}
    .wrap {{ padding:18px 14px }}
    .stats {{ grid-template-columns:repeat(2,1fr); gap:8px }}
    .stat {{ padding:14px }}
    .stat .val {{ font-size:22px }}
    h2 {{ font-size:16px }}
    .agent-grid {{ grid-template-columns:1fr; gap:10px }}
    .agent-card {{ padding:14px }}
    .primary-cta {{ padding:16px 18px; font-size:14px }}
    .trend-summary {{ grid-template-columns:repeat(2,1fr); gap:10px }}
    .trend-value {{ font-size:18px }}
    .history-table th, .history-table td {{ padding:8px 12px; font-size:11px }}
  }}
  @media (max-width:480px) {{
    .stats {{ grid-template-columns:1fr; gap:6px }}
    .hero h1 {{ font-size:20px }}
    .footer .contact-card {{ padding:14px 18px }}
  }}
  /* Trend chart */
  .trend-card {{ background:#161b22; border:1px solid #30363d; border-radius:8px;
                padding:18px 22px; margin:24px 0 }}
  .trend-summary {{ display:grid;
                   grid-template-columns:repeat(auto-fit, minmax(120px, 1fr));
                   gap:16px; margin-bottom:14px }}
  .trend-label {{ font-size:11px; color:#8b949e; text-transform:uppercase;
                 letter-spacing:.5px }}
  .trend-value {{ font-size:24px; font-weight:700; margin-top:2px }}
  .trend-svg   {{ width:100%; height:120px; display:block }}
  .trend-alerts{{ margin-top:14px; padding:12px 16px;
                 background:#2d1b1b; border-left:3px solid #f85149;
                 border-radius:6px }}
  .trend-alerts-title {{ font-weight:700; color:#f85149; margin-bottom:6px;
                        font-size:13px }}
  .trend-alerts ul {{ margin:0; padding-left:18px; color:#e6edf3; font-size:12px }}
  .trend-alerts li {{ margin:3px 0 }}
</style>
</head>
<body>

<div class="hero">
  <div class="hero-inner">
    <h1>🤖 Mehad Autonomous QA Report</h1>
    <div class="sub">{len(AGENT_REPORTS)} AI agents · {t or '—'} tests · auto-generated bug tickets · zero API cost</div>
    <div class="meta">
      <span><b>Run:</b> #{RUN_NUMBER}</span>
      <span><b>Commit:</b> <a href="https://github.com/{os.getenv('GITHUB_REPOSITORY','')}/commit/{os.getenv('GITHUB_SHA','')}">{COMMIT_SHA}</a></span>
      <span><b>Target:</b> {base_url or '—'}</span>
      <span><b>Generated:</b> {when_short}</span>
      <span><a href="{RUN_URL}">View CI run on GitHub →</a></span>
    </div>
  </div>
</div>

<div class="wrap">

  <div class="stats">{stats_html}</div>

  <a class="primary-cta" href="report.html">
    📊 View the full master bug report →
    <div class="cta-sub">Every test, every bug, with screenshots and friendly explanations</div>
  </a>

  {trend_html}

  <h2>📂 Per-Agent Reports</h2>
  <p style="color:#8b949e;font-size:13px;margin:0 0 16px">
    Each QA agent produces its own pytest-html report. Click a card to see
    just that agent's results.
  </p>
  <div class="agent-grid">{agent_grid}</div>

  <h2>🕐 History</h2>
  <p style="color:#8b949e;font-size:13px;margin:0 0 16px">
    Past runs are archived — click to compare against earlier baselines.
  </p>
  {history_html}

  <div class="footer">
    <div style="margin-bottom:6px">Built by Mehad Autonomous AI Test Agent · 100% local AI · no third-party API keys</div>
    <div class="contact-card">
      <div class="name">Mejbaur Bahar Fagun</div>
      <div class="title">Senior Software Engineer QA (IV) · Markopolo.ai</div>
      <div class="links"><a href="https://www.linkedin.com/in/mejbaur/" target="_blank" rel="noopener">💼 LinkedIn</a></div>
    </div>
  </div>

</div>

</body></html>"""


def _archive_dir() -> Path:
    """Per-run archive folder where this run's individual reports go."""
    arc = SITE_DIR / "history" / f"run-{RUN_NUMBER}"
    arc.mkdir(parents=True, exist_ok=True)
    return arc


def main() -> None:
    SITE_DIR.mkdir(exist_ok=True)
    (SITE_DIR / "agents").mkdir(exist_ok=True)
    (SITE_DIR / "history").mkdir(exist_ok=True)
    archive = _archive_dir()

    # 1. Master report at /report.html (and archived copy at /history/run-N.html)
    master = REPORTS_DIR / "bug-report.html"
    if master.exists():
        shutil.copy(master, SITE_DIR / "report.html")
        shutil.copy(master, SITE_DIR / "history" / f"run-{RUN_NUMBER}.html")
        print(f"  ✅ master report → report.html  +  history/run-{RUN_NUMBER}.html")
    else:
        print("  ⚠️  reports/bug-report.html not found — site will have no master report")

    # 1b. Copy the embedded-videos directory so <video src="videos-embed/..."> works.
    videos_embed = REPORTS_DIR / "videos-embed"
    if videos_embed.exists() and any(videos_embed.iterdir()):
        dest_videos = SITE_DIR / "videos-embed"
        if dest_videos.exists():
            shutil.rmtree(dest_videos)
        shutil.copytree(videos_embed, dest_videos)
        # Also copy into archived per-run folder so historical reports keep their videos
        shutil.copytree(videos_embed, archive / "videos-embed")
        n_videos = sum(1 for _ in dest_videos.glob("*.webm"))
        print(f"  ✅ videos-embed/ copied ({n_videos} video(s))")

    # 1c. Persist trends.json on the site root so the next CI run can fetch
    # it via https://<owner>.github.io/<repo>/trends.json — this is what
    # makes cumulative trend tracking actually work across runs.
    trends_src = REPORTS_DIR / "trends.json"
    if trends_src.exists():
        shutil.copy(trends_src, SITE_DIR / "trends.json")
        # Also save a per-run snapshot for historical inspection
        shutil.copy(trends_src, archive / "trends.json")
        print(f"  ✅ trends.json published to site root")

    # 1d. Publish AI test-code cache so the next CI run can reuse generated
    # tests for unchanged specs (skips slow Ollama calls). cache/tests/<slug>.json
    # is fetched at the start of the next run via _restore_cache_from_gh_pages.
    cache_dir = ROOT / "cache" / "tests"
    if cache_dir.exists() and any(cache_dir.iterdir()):
        dest_cache = SITE_DIR / "cache" / "tests"
        if dest_cache.exists():
            shutil.rmtree(dest_cache)
        dest_cache.mkdir(parents=True, exist_ok=True)
        for f in cache_dir.glob("*.json"):
            shutil.copy(f, dest_cache / f.name)
        n = sum(1 for _ in dest_cache.glob("*.json"))
        print(f"  ✅ AI test cache published ({n} spec(s) cached)")

    # 2. Per-agent reports under /agents/ (and archived copy). Prefer the
    #    custom Mehad-styled `agent-<src>.html` over the default pytest-html
    #    output. Fall back to pytest-html only if no custom report exists.
    found_agents = 0
    for custom_src, public_name, _label, _emoji in AGENT_REPORTS:
        src = _has_agent_report(custom_src, public_name)
        if src is not None:
            shutil.copy(src, SITE_DIR / "agents" / public_name)
            (archive / "agents").mkdir(exist_ok=True)
            shutil.copy(src, archive / "agents" / public_name)
            found_agents += 1
    print(f"  ✅ per-agent reports: {found_agents}/{len(AGENT_REPORTS)}")

    # 3. Build index.html
    summary = _load_summary()
    # History sources, in priority order:
    #   (a) trends.json — cumulative across all runs (gh-pages backed),
    #       knows about runs even if their run-N.html was cleaned up
    #   (b) local SITE_DIR/history/run-*.html — files the build script
    #       just emitted or copied into the deploy dir
    #   (c) the current RUN_NUMBER itself (so a fresh first deployment shows up)
    # Then dedupe BY RUN NUMBER (not by Path tuple — Path strings differ
    # between absolute filesystem entries and relative href strings, which
    # was causing duplicate "Run #N" rows to appear).
    history_runs: dict[int, Path] = {}
    for n, p in _existing_history(SITE_DIR):
        history_runs[n] = Path(f"history/run-{n}.html")
    # Pull every run number trends.json knows about
    try:
        trends_path = SITE_DIR / "trends.json"
        if trends_path.exists():
            tdata = json.loads(trends_path.read_text(encoding="utf-8"))
            for entry in tdata.get("history", []) or tdata.get("runs", []):
                n = entry.get("run") or entry.get("run_number")
                if n is not None:
                    try:
                        history_runs.setdefault(int(n),
                                                  Path(f"history/run-{int(n)}.html"))
                    except (TypeError, ValueError):
                        pass
    except Exception as e:
        print(f"  ⚠️  Could not merge trends.json into history: {e}")
    # Always include the current run if its html was emitted
    if (SITE_DIR / "history" / f"run-{RUN_NUMBER}.html").exists():
        try:
            n = int(RUN_NUMBER)
            history_runs[n] = Path(f"history/run-{n}.html")
        except Exception:
            pass
    history = sorted(history_runs.items(), reverse=True)

    (SITE_DIR / "index.html").write_text(
        _build_index_html(summary, history), encoding="utf-8")
    print(f"  ✅ index.html built ({len(history)} runs in history)")

    # 4. History index page (with unified footer)
    rows = []
    for run_num, _ in history[:50]:
        rows.append(f'<li><a href="run-{run_num}.html">Run #{run_num}</a></li>')
    (SITE_DIR / "history" / "index.html").write_text(f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Mehad QA — History</title>
<style>
* {{ box-sizing:border-box }}
body{{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;
     background:#0d1117;color:#e6edf3;padding:32px;max-width:720px;margin:0 auto;
     line-height:1.5}}
h1{{color:#58a6ff;margin-top:0}}
a{{color:#58a6ff;text-decoration:none}}
a:hover{{text-decoration:underline}}
ul{{list-style:none;padding:0}}
li{{padding:10px 12px;border-bottom:1px solid #30363d;border-radius:4px;
   transition:background .12s}}
li:hover{{background:#161b22}}
.footer{{margin-top:44px;padding:24px 12px;text-align:center;
        color:#8b949e;font-size:12px;border-top:1px solid #30363d}}
.footer .contact-card{{display:inline-flex;flex-direction:column;align-items:center;
                      gap:6px;padding:18px 28px;margin:14px auto 0;
                      background:#161b22;border:1px solid #30363d;border-radius:10px}}
.footer .contact-card .name {{font-weight:700;font-size:15px;color:#e6edf3}}
.footer .contact-card .title{{font-size:12px;color:#8b949e}}
.footer .contact-card .links a{{display:inline-block;color:#58a6ff;
                               font-size:12px;padding:5px 14px;margin-top:8px;
                               border:1px solid #30363d;border-radius:6px;
                               background:#0d1117}}
.footer .contact-card .links a:hover{{background:#1c2333;border-color:#58a6ff}}
@media (max-width:480px) {{ body{{padding:16px}} h1{{font-size:22px}} }}
</style></head>
<body>
<h1>QA Report History</h1>
<p><a href="../index.html">← Back to latest</a></p>
<ul>{"".join(rows)}</ul>
<div class="footer">
  <div style="margin-bottom:6px">Built by Mehad Autonomous AI Test Agent · 100% local AI · no third-party API keys</div>
  <div class="contact-card">
    <div class="name">Mejbaur Bahar Fagun</div>
    <div class="title">Senior Software Engineer QA (IV) · Markopolo.ai</div>
    <div class="links"><a href="https://www.linkedin.com/in/mejbaur/" target="_blank" rel="noopener">💼 LinkedIn</a></div>
  </div>
</div>
</body></html>""", encoding="utf-8")
    print(f"  ✅ history/index.html with {len(history)} entries")

    print(f"\nSite ready at: {SITE_DIR}")
    print(f"Files: {sum(1 for _ in SITE_DIR.rglob('*.html'))} HTML pages")


if __name__ == "__main__":
    main()
